version = 1

test_patterns = [
  "test/**",
  "*test.js"
]

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser",
    "cypress"
  ]

[[transformers]]
name = "prettier"

[[transformers]]
name = "rubocop"