version = 1
exclude_patterns = [
  "pnpm-lock.yaml",
]

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "javascript"

[analyzers.meta]
environment = [
  "nodejs",
  "browser",
]

[[analyzers]]
name = "docker"

[analyzers.meta]
dockerfile_paths = [".devcontainer/experimental/Dockerfile"]
